INSERT INTO OPERATION (ID, OPERATION_TYPE, COST) VALUES (1, 'ADDITION', 10);
INSERT INTO OPERATION (ID, OPERATION_TYPE, COST) VALUES (2, 'SUBTRACTION', 20);
INSERT INTO OPERATION (ID, OPERATION_TYPE, COST) VALUES (3, 'MULTIPLICATION', 30);
INSERT INTO OPERATION (ID, OPERATION_TYPE, COST) VALUES (4, 'DIVISION', 40);
INSERT INTO OPERATION (ID, OPERATION_TYPE, COST) VALUES (5, 'SQUARE_ROOT', 50);
INSERT INTO OPERATION (ID, OPERATION_TYPE, COST) VALUES (6, 'RANDOM_STRING', 60);